// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializechannelHeartRequest")
public inline fun channelHeartRequest(block: top.focess.netdesign.proto.ChannelHeartRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ChannelHeartRequest =
  top.focess.netdesign.proto.ChannelHeartRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.ChannelHeartRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 17 server packet0 return ClientAckResponse
 * ```
 *
 * Protobuf type `netdesign2.ChannelHeartRequest`
 */
public object ChannelHeartRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.ChannelHeartRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.ChannelHeartRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.ChannelHeartRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.ChannelHeartRequest.copy(block: `top.focess.netdesign.proto`.ChannelHeartRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ChannelHeartRequest =
  `top.focess.netdesign.proto`.ChannelHeartRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

