// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializecontactListRequest")
public inline fun contactListRequest(block: top.focess.netdesign.proto.ContactListRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ContactListRequest =
  top.focess.netdesign.proto.ContactListRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.ContactListRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 8
 * ```
 *
 * Protobuf type `netdesign2.ContactListRequest`
 */
public object ContactListRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.ContactListRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.ContactListRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.ContactListRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.ContactListRequest.copy(block: `top.focess.netdesign.proto`.ContactListRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ContactListRequest =
  `top.focess.netdesign.proto`.ContactListRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

