// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializecontactListResponse")
public inline fun contactListResponse(block: top.focess.netdesign.proto.ContactListResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ContactListResponse =
  top.focess.netdesign.proto.ContactListResponseKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.ContactListResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 9
 * ```
 *
 * Protobuf type `netdesign2.ContactListResponse`
 */
public object ContactListResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.ContactListResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.ContactListResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.ContactListResponse = _builder.build()

    /**
     * `int32 packetId = 1;`
     */
    public var packetId: kotlin.Int
      @JvmName("getPacketId")
      get() = _builder.getPacketId()
      @JvmName("setPacketId")
      set(value) {
        _builder.setPacketId(value)
      }
    /**
     * `int32 packetId = 1;`
     */
    public fun clearPacketId() {
      _builder.clearPacketId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ContactsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .netdesign2.Contact contacts = 2;`
     */
     public val contacts: com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getContactsList()
      )
    /**
     * `repeated .netdesign2.Contact contacts = 2;`
     * @param value The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addContacts")
    public fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.add(value: top.focess.netdesign.proto.PacketOuterClass.Contact) {
      _builder.addContacts(value)
    }
    /**
     * `repeated .netdesign2.Contact contacts = 2;`
     * @param value The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignContacts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.plusAssign(value: top.focess.netdesign.proto.PacketOuterClass.Contact) {
      add(value)
    }
    /**
     * `repeated .netdesign2.Contact contacts = 2;`
     * @param values The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllContacts")
    public fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.addAll(values: kotlin.collections.Iterable<top.focess.netdesign.proto.PacketOuterClass.Contact>) {
      _builder.addAllContacts(values)
    }
    /**
     * `repeated .netdesign2.Contact contacts = 2;`
     * @param values The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllContacts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.plusAssign(values: kotlin.collections.Iterable<top.focess.netdesign.proto.PacketOuterClass.Contact>) {
      addAll(values)
    }
    /**
     * `repeated .netdesign2.Contact contacts = 2;`
     * @param index The index to set the value at.
     * @param value The contacts to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setContacts")
    public operator fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.set(index: kotlin.Int, value: top.focess.netdesign.proto.PacketOuterClass.Contact) {
      _builder.setContacts(index, value)
    }
    /**
     * `repeated .netdesign2.Contact contacts = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearContacts")
    public fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.clear() {
      _builder.clearContacts()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.ContactListResponse.copy(block: `top.focess.netdesign.proto`.ContactListResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ContactListResponse =
  `top.focess.netdesign.proto`.ContactListResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

