// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializecontactResponse")
public inline fun contactResponse(block: top.focess.netdesign.proto.ContactResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ContactResponse =
  top.focess.netdesign.proto.ContactResponseKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.ContactResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 11
 * ```
 *
 * Protobuf type `netdesign2.ContactResponse`
 */
public object ContactResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.ContactResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.ContactResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.ContactResponse = _builder.build()

    /**
     * `.netdesign2.Contact contact = 1;`
     */
    public var contact: top.focess.netdesign.proto.PacketOuterClass.Contact
      @JvmName("getContact")
      get() = _builder.getContact()
      @JvmName("setContact")
      set(value) {
        _builder.setContact(value)
      }
    /**
     * `.netdesign2.Contact contact = 1;`
     */
    public fun clearContact() {
      _builder.clearContact()
    }
    /**
     * `.netdesign2.Contact contact = 1;`
     * @return Whether the contact field is set.
     */
    public fun hasContact(): kotlin.Boolean {
      return _builder.hasContact()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.ContactResponse.copy(block: `top.focess.netdesign.proto`.ContactResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ContactResponse =
  `top.focess.netdesign.proto`.ContactResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val top.focess.netdesign.proto.PacketOuterClass.ContactResponseOrBuilder.contactOrNull: top.focess.netdesign.proto.PacketOuterClass.Contact?
  get() = if (hasContact()) getContact() else null

