// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializecontactListRequest")
public inline fun contactListRequest(block: top.focess.netdesign.proto.ContactListRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ContactListRequest =
  top.focess.netdesign.proto.ContactListRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.ContactListRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 8 server packet0 return ClientAckResponse
 * ```
 *
 * Protobuf type `netdesign2.ContactListRequest`
 */
public object ContactListRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.ContactListRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.ContactListRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.ContactListRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ContactsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * contacts should contain the user contact itself as a Friend
     * ```
     *
     * `repeated .netdesign2.Contact contacts = 1;`
     */
     public val contacts: com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getContactsList()
      )
    /**
     * ```
     * contacts should contain the user contact itself as a Friend
     * ```
     *
     * `repeated .netdesign2.Contact contacts = 1;`
     * @param value The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addContacts")
    public fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.add(value: top.focess.netdesign.proto.PacketOuterClass.Contact) {
      _builder.addContacts(value)
    }
    /**
     * ```
     * contacts should contain the user contact itself as a Friend
     * ```
     *
     * `repeated .netdesign2.Contact contacts = 1;`
     * @param value The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignContacts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.plusAssign(value: top.focess.netdesign.proto.PacketOuterClass.Contact) {
      add(value)
    }
    /**
     * ```
     * contacts should contain the user contact itself as a Friend
     * ```
     *
     * `repeated .netdesign2.Contact contacts = 1;`
     * @param values The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllContacts")
    public fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.addAll(values: kotlin.collections.Iterable<top.focess.netdesign.proto.PacketOuterClass.Contact>) {
      _builder.addAllContacts(values)
    }
    /**
     * ```
     * contacts should contain the user contact itself as a Friend
     * ```
     *
     * `repeated .netdesign2.Contact contacts = 1;`
     * @param values The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllContacts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.plusAssign(values: kotlin.collections.Iterable<top.focess.netdesign.proto.PacketOuterClass.Contact>) {
      addAll(values)
    }
    /**
     * ```
     * contacts should contain the user contact itself as a Friend
     * ```
     *
     * `repeated .netdesign2.Contact contacts = 1;`
     * @param index The index to set the value at.
     * @param value The contacts to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setContacts")
    public operator fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.set(index: kotlin.Int, value: top.focess.netdesign.proto.PacketOuterClass.Contact) {
      _builder.setContacts(index, value)
    }
    /**
     * ```
     * contacts should contain the user contact itself as a Friend
     * ```
     *
     * `repeated .netdesign2.Contact contacts = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearContacts")
    public fun com.google.protobuf.kotlin.DslList<top.focess.netdesign.proto.PacketOuterClass.Contact, ContactsProxy>.clear() {
      _builder.clearContacts()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class InternalIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated int32 internalIds = 2;`
     */
     public val internalIds: com.google.protobuf.kotlin.DslList<kotlin.Int, InternalIdsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getInternalIdsList()
      )
    /**
     * `repeated int32 internalIds = 2;`
     * @param value The internalIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addInternalIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, InternalIdsProxy>.add(value: kotlin.Int) {
      _builder.addInternalIds(value)
    }/**
     * `repeated int32 internalIds = 2;`
     * @param value The internalIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignInternalIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, InternalIdsProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * `repeated int32 internalIds = 2;`
     * @param values The internalIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllInternalIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, InternalIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllInternalIds(values)
    }/**
     * `repeated int32 internalIds = 2;`
     * @param values The internalIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllInternalIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, InternalIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * `repeated int32 internalIds = 2;`
     * @param index The index to set the value at.
     * @param value The internalIds to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setInternalIds")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, InternalIdsProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setInternalIds(index, value)
    }/**
     * `repeated int32 internalIds = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearInternalIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, InternalIdsProxy>.clear() {
      _builder.clearInternalIds()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.ContactListRequest.copy(block: `top.focess.netdesign.proto`.ContactListRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ContactListRequest =
  `top.focess.netdesign.proto`.ContactListRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

