// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializecontactRequest")
public inline fun contactRequest(block: top.focess.netdesign.proto.ContactRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ContactRequest =
  top.focess.netdesign.proto.ContactRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.ContactRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 10 server packet0 return ClientAckResponse
 * ```
 *
 * Protobuf type `netdesign2.ContactRequest`
 */
public object ContactRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.ContactRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.ContactRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.ContactRequest = _builder.build()

    /**
     * `.netdesign2.Contact contact = 1;`
     */
    public var contact: top.focess.netdesign.proto.PacketOuterClass.Contact
      @JvmName("getContact")
      get() = _builder.getContact()
      @JvmName("setContact")
      set(value) {
        _builder.setContact(value)
      }
    /**
     * `.netdesign2.Contact contact = 1;`
     */
    public fun clearContact() {
      _builder.clearContact()
    }
    /**
     * `.netdesign2.Contact contact = 1;`
     * @return Whether the contact field is set.
     */
    public fun hasContact(): kotlin.Boolean {
      return _builder.hasContact()
    }

    /**
     * `bool delete = 2;`
     */
    public var delete: kotlin.Boolean
      @JvmName("getDelete")
      get() = _builder.getDelete()
      @JvmName("setDelete")
      set(value) {
        _builder.setDelete(value)
      }
    /**
     * `bool delete = 2;`
     */
    public fun clearDelete() {
      _builder.clearDelete()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.ContactRequest.copy(block: `top.focess.netdesign.proto`.ContactRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ContactRequest =
  `top.focess.netdesign.proto`.ContactRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val top.focess.netdesign.proto.PacketOuterClass.ContactRequestOrBuilder.contactOrNull: top.focess.netdesign.proto.PacketOuterClass.Contact?
  get() = if (hasContact()) getContact() else null

