// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializedeleteMessageResponse")
public inline fun deleteMessageResponse(block: top.focess.netdesign.proto.DeleteMessageResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.DeleteMessageResponse =
  top.focess.netdesign.proto.DeleteMessageResponseKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.DeleteMessageResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 26 server packet
 * ```
 *
 * Protobuf type `netdesign2.DeleteMessageResponse`
 */
public object DeleteMessageResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.DeleteMessageResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.DeleteMessageResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.DeleteMessageResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.DeleteMessageResponse.copy(block: `top.focess.netdesign.proto`.DeleteMessageResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.DeleteMessageResponse =
  `top.focess.netdesign.proto`.DeleteMessageResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

