// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializefileUploadRequest")
public inline fun fileUploadRequest(block: top.focess.netdesign.proto.FileUploadRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.FileUploadRequest =
  top.focess.netdesign.proto.FileUploadRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.FileUploadRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 19 client packet return ServerAckResponse
 * ```
 *
 * Protobuf type `netdesign2.FileUploadRequest`
 */
public object FileUploadRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.FileUploadRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.FileUploadRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.FileUploadRequest = _builder.build()

    /**
     * `string token = 1;`
     */
    public var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * `string token = 1;`
     */
    public fun clearToken() {
      _builder.clearToken()
    }

    /**
     * `string id = 2;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 2;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `.netdesign2.File file = 3;`
     */
    public var file: top.focess.netdesign.proto.PacketOuterClass.File
      @JvmName("getFile")
      get() = _builder.getFile()
      @JvmName("setFile")
      set(value) {
        _builder.setFile(value)
      }
    /**
     * `.netdesign2.File file = 3;`
     */
    public fun clearFile() {
      _builder.clearFile()
    }
    /**
     * `.netdesign2.File file = 3;`
     * @return Whether the file field is set.
     */
    public fun hasFile(): kotlin.Boolean {
      return _builder.hasFile()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.FileUploadRequest.copy(block: `top.focess.netdesign.proto`.FileUploadRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.FileUploadRequest =
  `top.focess.netdesign.proto`.FileUploadRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val top.focess.netdesign.proto.PacketOuterClass.FileUploadRequestOrBuilder.fileOrNull: top.focess.netdesign.proto.PacketOuterClass.File?
  get() = if (hasFile()) getFile() else null

