// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializefriendInfoResponse")
public inline fun friendInfoResponse(block: top.focess.netdesign.proto.FriendInfoResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.FriendInfoResponse =
  top.focess.netdesign.proto.FriendInfoResponseKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.FriendInfoResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 11
 * ```
 *
 * Protobuf type `netdesign2.FriendInfoResponse`
 */
public object FriendInfoResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.FriendInfoResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.FriendInfoResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.FriendInfoResponse = _builder.build()

    /**
     * `int32 packetId = 1;`
     */
    public var packetId: kotlin.Int
      @JvmName("getPacketId")
      get() = _builder.getPacketId()
      @JvmName("setPacketId")
      set(value) {
        _builder.setPacketId(value)
      }
    /**
     * `int32 packetId = 1;`
     */
    public fun clearPacketId() {
      _builder.clearPacketId()
    }

    /**
     * `int32 id = 2;`
     */
    public var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `int32 id = 2;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 3;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 3;`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.FriendInfoResponse.copy(block: `top.focess.netdesign.proto`.FriendInfoResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.FriendInfoResponse =
  `top.focess.netdesign.proto`.FriendInfoResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

