// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializefriendSendMessageResponse")
public inline fun friendSendMessageResponse(block: top.focess.netdesign.proto.FriendSendMessageResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.FriendSendMessageResponse =
  top.focess.netdesign.proto.FriendSendMessageResponseKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.FriendSendMessageResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 15 server packet
 * ```
 *
 * Protobuf type `netdesign2.FriendSendMessageResponse`
 */
public object FriendSendMessageResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.FriendSendMessageResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.FriendSendMessageResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.FriendSendMessageResponse = _builder.build()

    /**
     * ```
     * fail if message.id == -1
     * ```
     *
     * `.netdesign2.Message message = 1;`
     */
    public var message: top.focess.netdesign.proto.PacketOuterClass.Message
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * ```
     * fail if message.id == -1
     * ```
     *
     * `.netdesign2.Message message = 1;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
    /**
     * ```
     * fail if message.id == -1
     * ```
     *
     * `.netdesign2.Message message = 1;`
     * @return Whether the message field is set.
     */
    public fun hasMessage(): kotlin.Boolean {
      return _builder.hasMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.FriendSendMessageResponse.copy(block: `top.focess.netdesign.proto`.FriendSendMessageResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.FriendSendMessageResponse =
  `top.focess.netdesign.proto`.FriendSendMessageResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val top.focess.netdesign.proto.PacketOuterClass.FriendSendMessageResponseOrBuilder.messageOrNull: top.focess.netdesign.proto.PacketOuterClass.Message?
  get() = if (hasMessage()) getMessage() else null

