// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializefriendInfoRequest")
public inline fun friendInfoRequest(block: top.focess.netdesign.proto.FriendInfoRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.FriendInfoRequest =
  top.focess.netdesign.proto.FriendInfoRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.FriendInfoRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 10
 * ```
 *
 * Protobuf type `netdesign2.FriendInfoRequest`
 */
public object FriendInfoRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.FriendInfoRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.FriendInfoRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.FriendInfoRequest = _builder.build()

    /**
     * `int32 packetId = 1;`
     */
    public var packetId: kotlin.Int
      @JvmName("getPacketId")
      get() = _builder.getPacketId()
      @JvmName("setPacketId")
      set(value) {
        _builder.setPacketId(value)
      }
    /**
     * `int32 packetId = 1;`
     */
    public fun clearPacketId() {
      _builder.clearPacketId()
    }

    /**
     * `int32 id = 2;`
     */
    public var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `int32 id = 2;`
     */
    public fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.FriendInfoRequest.copy(block: `top.focess.netdesign.proto`.FriendInfoRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.FriendInfoRequest =
  `top.focess.netdesign.proto`.FriendInfoRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

