// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializeloginPreResponse")
public inline fun loginPreResponse(block: top.focess.netdesign.proto.LoginPreResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.LoginPreResponse =
  top.focess.netdesign.proto.LoginPreResponseKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.LoginPreResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 3
 * ```
 *
 * Protobuf type `netdesign2.LoginPreResponse`
 */
public object LoginPreResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.LoginPreResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.LoginPreResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.LoginPreResponse = _builder.build()

    /**
     * `string challenge = 1;`
     */
    public var challenge: kotlin.String
      @JvmName("getChallenge")
      get() = _builder.getChallenge()
      @JvmName("setChallenge")
      set(value) {
        _builder.setChallenge(value)
      }
    /**
     * `string challenge = 1;`
     */
    public fun clearChallenge() {
      _builder.clearChallenge()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.LoginPreResponse.copy(block: `top.focess.netdesign.proto`.LoginPreResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.LoginPreResponse =
  `top.focess.netdesign.proto`.LoginPreResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

