// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializeloginRequest")
public inline fun loginRequest(block: top.focess.netdesign.proto.LoginRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.LoginRequest =
  top.focess.netdesign.proto.LoginRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.LoginRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 4
 * ```
 *
 * Protobuf type `netdesign2.LoginRequest`
 */
public object LoginRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.LoginRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.LoginRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.LoginRequest = _builder.build()

    /**
     * `string username = 1;`
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * `string hashPassword = 2;`
     */
    public var hashPassword: kotlin.String
      @JvmName("getHashPassword")
      get() = _builder.getHashPassword()
      @JvmName("setHashPassword")
      set(value) {
        _builder.setHashPassword(value)
      }
    /**
     * `string hashPassword = 2;`
     */
    public fun clearHashPassword() {
      _builder.clearHashPassword()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.LoginRequest.copy(block: `top.focess.netdesign.proto`.LoginRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.LoginRequest =
  `top.focess.netdesign.proto`.LoginRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

