// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializeloginResponse")
public inline fun loginResponse(block: top.focess.netdesign.proto.LoginResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.LoginResponse =
  top.focess.netdesign.proto.LoginResponseKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.LoginResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 5 server packet
 * ```
 *
 * Protobuf type `netdesign2.LoginResponse`
 */
public object LoginResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.LoginResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.LoginResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.LoginResponse = _builder.build()

    /**
     * `string username = 1;`
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * `bool logined = 2;`
     */
    public var logined: kotlin.Boolean
      @JvmName("getLogined")
      get() = _builder.getLogined()
      @JvmName("setLogined")
      set(value) {
        _builder.setLogined(value)
      }
    /**
     * `bool logined = 2;`
     */
    public fun clearLogined() {
      _builder.clearLogined()
    }

    /**
     * `string token = 3;`
     */
    public var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * `string token = 3;`
     */
    public fun clearToken() {
      _builder.clearToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.LoginResponse.copy(block: `top.focess.netdesign.proto`.LoginResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.LoginResponse =
  `top.focess.netdesign.proto`.LoginResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

