// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializepacket")
public inline fun packet(block: top.focess.netdesign.proto.PacketKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.Packet =
  top.focess.netdesign.proto.PacketKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.Packet.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `netdesign2.Packet`
 */
public object PacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.Packet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.Packet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.Packet = _builder.build()

    /**
     * `int32 packetId = 1;`
     */
    public var packetId: kotlin.Int
      @JvmName("getPacketId")
      get() = _builder.getPacketId()
      @JvmName("setPacketId")
      set(value) {
        _builder.setPacketId(value)
      }
    /**
     * `int32 packetId = 1;`
     */
    public fun clearPacketId() {
      _builder.clearPacketId()
    }

    /**
     * `.google.protobuf.Any content = 2;`
     */
    public var content: com.google.protobuf.Any
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * `.google.protobuf.Any content = 2;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }
    /**
     * `.google.protobuf.Any content = 2;`
     * @return Whether the content field is set.
     */
    public fun hasContent(): kotlin.Boolean {
      return _builder.hasContent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.Packet.copy(block: `top.focess.netdesign.proto`.PacketKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.Packet =
  `top.focess.netdesign.proto`.PacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val top.focess.netdesign.proto.PacketOuterClass.PacketOrBuilder.contentOrNull: com.google.protobuf.Any?
  get() = if (hasContent()) getContent() else null

