// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializeregisterRequest")
public inline fun registerRequest(block: top.focess.netdesign.proto.RegisterRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.RegisterRequest =
  top.focess.netdesign.proto.RegisterRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.RegisterRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 22 client packet
 * ```
 *
 * Protobuf type `netdesign2.RegisterRequest`
 */
public object RegisterRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.RegisterRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.RegisterRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.RegisterRequest = _builder.build()

    /**
     * `string username = 1;`
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * `string rawPassword = 2;`
     */
    public var rawPassword: kotlin.String
      @JvmName("getRawPassword")
      get() = _builder.getRawPassword()
      @JvmName("setRawPassword")
      set(value) {
        _builder.setRawPassword(value)
      }
    /**
     * `string rawPassword = 2;`
     */
    public fun clearRawPassword() {
      _builder.clearRawPassword()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.RegisterRequest.copy(block: `top.focess.netdesign.proto`.RegisterRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.RegisterRequest =
  `top.focess.netdesign.proto`.RegisterRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

