// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializesendMessageRequest")
public inline fun sendMessageRequest(block: top.focess.netdesign.proto.SendMessageRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.SendMessageRequest =
  top.focess.netdesign.proto.SendMessageRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.SendMessageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 14 client packet
 * ```
 *
 * Protobuf type `netdesign2.SendMessageRequest`
 */
public object SendMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.SendMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.SendMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.SendMessageRequest = _builder.build()

    /**
     * `string token = 1;`
     */
    public var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * `string token = 1;`
     */
    public fun clearToken() {
      _builder.clearToken()
    }

    /**
     * `.netdesign2.RawMessage message = 2;`
     */
    public var message: top.focess.netdesign.proto.PacketOuterClass.RawMessage
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `.netdesign2.RawMessage message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
    /**
     * `.netdesign2.RawMessage message = 2;`
     * @return Whether the message field is set.
     */
    public fun hasMessage(): kotlin.Boolean {
      return _builder.hasMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.SendMessageRequest.copy(block: `top.focess.netdesign.proto`.SendMessageRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.SendMessageRequest =
  `top.focess.netdesign.proto`.SendMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val top.focess.netdesign.proto.PacketOuterClass.SendMessageRequestOrBuilder.messageOrNull: top.focess.netdesign.proto.PacketOuterClass.RawMessage?
  get() = if (hasMessage()) getMessage() else null

