// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializeserverAckResponse")
public inline fun serverAckResponse(block: top.focess.netdesign.proto.ServerAckResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ServerAckResponse =
  top.focess.netdesign.proto.ServerAckResponseKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.ServerAckResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 11 server packet, packet0
 * ```
 *
 * Protobuf type `netdesign2.ServerAckResponse`
 */
public object ServerAckResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.ServerAckResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.ServerAckResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.ServerAckResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.ServerAckResponse.copy(block: `top.focess.netdesign.proto`.ServerAckResponseKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ServerAckResponse =
  `top.focess.netdesign.proto`.ServerAckResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

