// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializeserverStatusRequest")
public inline fun serverStatusRequest(block: top.focess.netdesign.proto.ServerStatusRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ServerStatusRequest =
  top.focess.netdesign.proto.ServerStatusRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.ServerStatusRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 0
 * ```
 *
 * Protobuf type `netdesign2.ServerStatusRequest`
 */
public object ServerStatusRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.ServerStatusRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.ServerStatusRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.ServerStatusRequest = _builder.build()

    /**
     * `optional string clientPublicKey = 1;`
     */
    public var clientPublicKey: kotlin.String?
      @JvmName("getClientPublicKey")
      get() = _builder.getClientPublicKey()
      @JvmName("setClientPublicKey")
      set(value) {
        _builder.setClientPublicKey(value)
      }
    /**
     * `optional string clientPublicKey = 1;`
     */
    public fun clearClientPublicKey() {
      _builder.clearClientPublicKey()
    }
    /**
     * `optional string clientPublicKey = 1;`
     * @return Whether the clientPublicKey field is set.
     */
    public fun hasClientPublicKey(): kotlin.Boolean {
      return _builder.hasClientPublicKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.ServerStatusRequest.copy(block: `top.focess.netdesign.proto`.ServerStatusRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ServerStatusRequest =
  `top.focess.netdesign.proto`.ServerStatusRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

