// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/resources/protos/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package top.focess.netdesign.proto;

@kotlin.jvm.JvmName("-initializeserverStatusUpdateRequest")
public inline fun serverStatusUpdateRequest(block: top.focess.netdesign.proto.ServerStatusUpdateRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ServerStatusUpdateRequest =
  top.focess.netdesign.proto.ServerStatusUpdateRequestKt.Dsl._create(top.focess.netdesign.proto.PacketOuterClass.ServerStatusUpdateRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *packet id = 6 client packet
 * ```
 *
 * Protobuf type `netdesign2.ServerStatusUpdateRequest`
 */
public object ServerStatusUpdateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: top.focess.netdesign.proto.PacketOuterClass.ServerStatusUpdateRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: top.focess.netdesign.proto.PacketOuterClass.ServerStatusUpdateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): top.focess.netdesign.proto.PacketOuterClass.ServerStatusUpdateRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun top.focess.netdesign.proto.PacketOuterClass.ServerStatusUpdateRequest.copy(block: `top.focess.netdesign.proto`.ServerStatusUpdateRequestKt.Dsl.() -> kotlin.Unit): top.focess.netdesign.proto.PacketOuterClass.ServerStatusUpdateRequest =
  `top.focess.netdesign.proto`.ServerStatusUpdateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

