name: Build and Release

on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew packageReleaseDistributionForCurrentOS

    - name: Upload Release
      uses: actions/upload-artifact@v2
      with:
        name: NetDesign2
        path: build/binaries/**/*  # replace with the path to your built app
