name: Build and Release on Windows

on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: .\gradlew.bat packageReleaseDistributionForCurrentOS

      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: NetDesign2 Windows
          path: build\compose\binaries\main-release\msi\*